name: Monitor User

on:
  schedule:
    - cron: '*/90 * * * *'
  watch:
    types: started



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Set up Python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 'Install dependencies'
        run: pip install -r github/requirements.txt

      - name: 'Run script'
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PersonalAccessToken }}
        run: python github/monitor_user.py

      - name: Update data
        env:
          GITHUB_TOKEN: ${{ secrets.GithubToken }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PersonalAccessToken }}
        run: |
          mkdir -p data
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          git commit -m "ci: update data (automatically)" || exit 0
          git push
